SELECT [ID]
      ,[URL]
      ,[Title]
      ,[Type]
      ,[Price]
      ,[Rating]
      ,[Reviews]
      ,[Sold]
      ,[FechaExtraccion]
  FROM [MercadoLibre].[dbo].[ProductosMercadoLibre]
