SELECT TOP (1000) [ID]
      ,[URL]
      ,[Nombre]
      ,[Precio]
      ,[Calificacion]
      ,[Ventas]
      ,[ImagenURL]
      ,[FechaExtraccion]
  FROM [MercadoLibre].[dbo].[ProductosMercadoLibre]
